/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author felip
 */
class Produtos {

    private String codigo;
    private String nome;
    private int quant;
    private int quantCrit;

    Produtos(String codigo, String nome, int quant, int quantCrit) {
        this.codigo = codigo;
        this.nome = nome;
        this.quant = quant;
        this.quantCrit = quantCrit;
    }

    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public int getQuant() {
        return quant;
    }

    public void setQuant(int quant) {
        this.quant = quant;
    }

    public int getQuantCrit() {
        return quantCrit;
    }

    public void setQuantCrit(int quantCrit) {
        this.quantCrit = quantCrit;
    }

}

public class TelaProdutosVendas extends javax.swing.JFrame {

    /**
     * Creates new form TelaProdutos
     */
    public TelaProdutosVendas() {
        initComponents();
        jLabelAvisoTexto.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelX = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldQuantidade = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jButtonLimparVenda = new javax.swing.JButton();
        jButtonDeletar = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCritico = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        jButtonEditar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVendas = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCodigoVenda = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCodigoProd = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldQuantidadeVendas = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldPreco = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jFormattedTextField = new javax.swing.JFormattedTextField();
        jButtonVenda = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jLabelAvisoTexto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GERENCIAR PRODUTOS E VENDAS");

        jLabelX.setBackground(new java.awt.Color(255, 255, 255));
        jLabelX.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabelX.setForeground(new java.awt.Color(255, 255, 255));
        jLabelX.setText("X");
        jLabelX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelXMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 325, Short.MAX_VALUE)
                .addComponent(jLabelX)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelX))
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(1, 1, 1016, 54);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("CodigoProd");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(13, 106, 106, 27);

        jTextFieldCodigo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextFieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCodigo);
        jTextFieldCodigo.setBounds(193, 105, 150, 29);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setText("Nome");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(13, 153, 54, 27);

        jTextFieldNome.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jPanel1.add(jTextFieldNome);
        jTextFieldNome.setBounds(193, 152, 150, 29);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setText("Quantidade");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(13, 200, 106, 27);

        jTextFieldQuantidade.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextFieldQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldQuantidadeFocusLost(evt);
            }
        });
        jTextFieldQuantidade.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextFieldQuantidadeInputMethodTextChanged(evt);
            }
        });
        jTextFieldQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuantidadeActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldQuantidade);
        jTextFieldQuantidade.setBounds(193, 199, 150, 29);

        jButtonAdd.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonAdd.setText("ADD");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAdd);
        jButtonAdd.setBounds(40, 300, 68, 27);

        jButtonLimparVenda.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonLimparVenda.setText("LIMPAR");
        jButtonLimparVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparVendaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLimparVenda);
        jButtonLimparVenda.setBounds(370, 500, 100, 27);

        jButtonDeletar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonDeletar.setText("DELETAR");
        jButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDeletar);
        jButtonDeletar.setBounds(220, 300, 100, 27);

        jButtonHome.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonHome.setText("HOME");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonHome);
        jButtonHome.setBounds(90, 340, 90, 27);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 550, 1016, 11);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setText("LISTA DE PRODUTOS");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(608, 62, 167, 27);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setText("Quant. Crítica (10%)");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(13, 247, 175, 27);

        jTextFieldCritico.setEditable(false);
        jTextFieldCritico.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextFieldCritico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCriticoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCritico);
        jTextFieldCritico.setBounds(193, 246, 151, 29);

        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Quantidade", "Crítico", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdutosMouseClicked(evt);
            }
        });
        jTableProdutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableProdutosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProdutos);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(362, 96, 643, 214);

        jButtonEditar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonEditar.setText("EDITAR");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditar);
        jButtonEditar.setBounds(120, 300, 90, 27);

        jTableVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Produto", "Quantidade", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableVendas);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(545, 346, 460, 180);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setText("LISTA DE VENDAS");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(705, 317, 144, 27);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setText("CodigoVenda");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(13, 384, 125, 27);

        jTextFieldCodigoVenda.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextFieldCodigoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoVendaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCodigoVenda);
        jTextFieldCodigoVenda.setBounds(156, 383, 150, 29);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setText("CodigoProd");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(13, 420, 106, 27);

        jTextFieldCodigoProd.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextFieldCodigoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoProdActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldCodigoProd);
        jTextFieldCodigoProd.setBounds(156, 419, 150, 29);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setText("Quantidade");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(13, 456, 106, 27);

        jTextFieldQuantidadeVendas.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextFieldQuantidadeVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQuantidadeVendasActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldQuantidadeVendas);
        jTextFieldQuantidadeVendas.setBounds(156, 455, 150, 29);

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setText("Preço");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(13, 490, 52, 27);

        jTextFieldPreco.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextFieldPreco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPrecoFocusLost(evt);
            }
        });
        jTextFieldPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldPreco);
        jTextFieldPreco.setBounds(156, 492, 150, 29);

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setText("Total");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(330, 390, 41, 27);

        jFormattedTextField.setEditable(false);
        jFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jFormattedTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldFocusGained(evt);
            }
        });
        jPanel1.add(jFormattedTextField);
        jFormattedTextField.setBounds(390, 390, 130, 30);

        jButtonVenda.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonVenda.setText("ADICIONAR VENDA");
        jButtonVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVendaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVenda);
        jButtonVenda.setBounds(330, 460, 180, 27);

        jButtonLimpar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonLimpar.setText("LIMPAR");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLimpar);
        jButtonLimpar.setBounds(190, 340, 100, 27);

        jLabelAvisoTexto.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelAvisoTexto.setForeground(new java.awt.Color(255, 51, 51));
        jLabelAvisoTexto.setText("<html><body>1 ou mais produtos em estoque crítico.<br>");
        jPanel1.add(jLabelAvisoTexto);
        jLabelAvisoTexto.setBounds(790, 50, 210, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1018, 562));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        TelaMenuPrincipal menu = new TelaMenuPrincipal();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jTextFieldCriticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCriticoActionPerformed

    }//GEN-LAST:event_jTextFieldCriticoActionPerformed

    private void jTextFieldQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuantidadeActionPerformed

    }//GEN-LAST:event_jTextFieldQuantidadeActionPerformed

    private void jTextFieldQuantidadeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextFieldQuantidadeInputMethodTextChanged

    }//GEN-LAST:event_jTextFieldQuantidadeInputMethodTextChanged

    private void jTextFieldQuantidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldQuantidadeFocusLost
        int quant = (int) Math.floor(Double.parseDouble(jTextFieldQuantidade.getText()) * 0.1);
        jTextFieldCritico.setText(String.valueOf(quant));
    }//GEN-LAST:event_jTextFieldQuantidadeFocusLost

    private void jTextFieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        DefaultTableModel dtmProdutos = (DefaultTableModel) jTableProdutos.getModel();
        try {
            if (Integer.parseInt(jTextFieldQuantidade.getText()) < 0) {
                JOptionPane.showMessageDialog(null, """
                                                Processo n\u00e3o finalizado.
                                                Quantidade menor que 0.""");
            } else {
                Object[] dados = {jTextFieldCodigo.getText(), jTextFieldNome.getText(), jTextFieldQuantidade.getText(), jTextFieldCritico.getText(), Double.parseDouble(jTextFieldCritico.getText()) >= Double.parseDouble(jTextFieldQuantidade.getText()) ? "CRÍTICO" : "NÃO CRÍTICO"};
                dtmProdutos.addRow(dados);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher campos.");
        }

    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarActionPerformed
        if (jTableProdutos.getSelectedRow() != -1) {
            DefaultTableModel dtmProdutos = (DefaultTableModel) jTableProdutos.getModel();
            dtmProdutos.removeRow(jTableProdutos.getSelectedRow());
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir.");
        }

        if (jTableProdutos.getRowCount() == 0) {
            jLabelAvisoTexto.setVisible(false);
        } else {
            int countCrit = 0;

            for (int i = 0; i < jTableProdutos.getRowCount(); i++) {
                if (jTableProdutos.getValueAt(i, 4).toString().equals("CRÍTICO")) {
                    countCrit++;
                }
            }
            if (countCrit == 0) {
                jLabelAvisoTexto.setVisible(false);
            } else {
                jLabelAvisoTexto.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButtonDeletarActionPerformed

    private void jButtonLimparVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparVendaActionPerformed
        jTextFieldCodigoVenda.setText("");
        jTextFieldCodigoProd.setText("");
        jTextFieldQuantidadeVendas.setText("");
        jTextFieldPreco.setText("");
        jFormattedTextField.setText("");
    }//GEN-LAST:event_jButtonLimparVendaActionPerformed

    private void jTableProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutosMouseClicked
        if (jTableProdutos.getSelectedRow() != -1) {
            jTextFieldCodigo.setText(jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 0).toString());
            jTextFieldNome.setText(jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 1).toString());
            jTextFieldQuantidade.setText(jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 2).toString());
            jTextFieldCritico.setText(jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 3).toString());
        }
    }//GEN-LAST:event_jTableProdutosMouseClicked

    private void jTableProdutosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableProdutosKeyReleased
        // TODO add your handling code here:
        if (jTableProdutos.getSelectedRow() != -1) {
            jTextFieldCodigo.setText(jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 0).toString());
            jTextFieldNome.setText(jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 1).toString());
            jTextFieldQuantidade.setText(jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 2).toString());
            jTextFieldCritico.setText(jTableProdutos.getValueAt(jTableProdutos.getSelectedRow(), 3).toString());
        }
    }//GEN-LAST:event_jTableProdutosKeyReleased

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        if (jTableProdutos.getSelectedRow() != -1) {
            int rowAtual = jTableProdutos.getSelectedRow();
            jTableProdutos.setValueAt(jTextFieldCodigo.getText(), jTableProdutos.getSelectedRow(), 0);
            jTableProdutos.setValueAt(jTextFieldNome.getText(), jTableProdutos.getSelectedRow(), 1);
            jTableProdutos.setValueAt(jTextFieldQuantidade.getText(), jTableProdutos.getSelectedRow(), 2);
            jTableProdutos.setValueAt((int) Math.floor(Double.parseDouble(jTextFieldQuantidade.getText()) * 0.1), jTableProdutos.getSelectedRow(), 3);
                        
            if (Double.parseDouble(jTableProdutos.getValueAt(rowAtual, 2).toString()) > Double.parseDouble(jTableProdutos.getValueAt(rowAtual, 3).toString())) {
                jTableProdutos.setValueAt("NÃO CRÍTICO", rowAtual, 4);
                jLabelAvisoTexto.setVisible(false);
            }
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jTextFieldCodigoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoVendaActionPerformed

    private void jTextFieldCodigoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoProdActionPerformed

    private void jTextFieldQuantidadeVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuantidadeVendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQuantidadeVendasActionPerformed

    private void jTextFieldPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecoActionPerformed

    private void jButtonVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVendaActionPerformed
        // TODO add your handling code here:
        if (jTextFieldCodigoVenda.getText().equals("") || jTextFieldCodigoProd.getText().equals("") || jTextFieldQuantidadeVendas.getText().equals("") || jTextFieldPreco.getText().equals("") || (Integer.parseInt(jTextFieldQuantidadeVendas.getText()) < 0) || (Integer.parseInt(jTextFieldPreco.getText()) < 0)) {
            JOptionPane.showMessageDialog(null, "Erro ao preencher campos.");
        } else {
            if (Double.parseDouble(jTextFieldPreco.getText()) < 0) {
                JOptionPane.showMessageDialog(null, """
                                                Compra n\u00e3o finalizada.
                                                Pre\u00e7o menor que 0.""");
            } else {
                DefaultTableModel dtmVendas = (DefaultTableModel) jTableVendas.getModel();
                int i = 0;
                Object nomeProduto = null;
                int valorCodigo = Integer.parseInt(jTextFieldCodigoProd.getText());
                for (i = 0; i < jTableProdutos.getRowCount(); i++) {
                    if (valorCodigo == Integer.parseInt(jTableProdutos.getValueAt(i, 0).toString())) {
                        if (Integer.parseInt(jTableProdutos.getValueAt(i, 2).toString()) - Integer.parseInt(jTextFieldQuantidadeVendas.getText()) < 0) {
                            JOptionPane.showMessageDialog(null, """
                                                            Compra n\u00e3o finalizada
                                                            Quantidade insuficiente no estoque.""");
                        } else {
                            nomeProduto = jTableProdutos.getValueAt(i, 1);
                            int quantVendida = Integer.parseInt(jTextFieldQuantidadeVendas.getText());
                            int quantDisponivel = Integer.parseInt(jTableProdutos.getValueAt(i, 2).toString());
                            Object novaQuant = quantDisponivel - quantVendida;
                            jTableProdutos.setValueAt(novaQuant, i, 2);

                            Object[] dados = {jTextFieldCodigoVenda.getText(), nomeProduto.toString(), jTextFieldQuantidadeVendas.getText(), jFormattedTextField.getText()};
                            dtmVendas.addRow(dados);

                            if (Double.parseDouble(jTableProdutos.getValueAt(i, 3).toString()) >= Double.parseDouble(jTableProdutos.getValueAt(i, 2).toString())) {
                                jTableProdutos.setValueAt("CRÍTICO", i, 4);
                                jLabelAvisoTexto.setVisible(true);
                            }
                        }
                    }
                }
            }
        }


    }//GEN-LAST:event_jButtonVendaActionPerformed

    private void jTextFieldPrecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPrecoFocusLost
        // TODO add your handling code here:
        double quantidade = Double.parseDouble(jTextFieldQuantidadeVendas.getText());
        double preco = Double.parseDouble(jTextFieldPreco.getText());
        double total = quantidade * preco;
        String totalF = String.format("%.02f", total);
        jFormattedTextField.setText(totalF);
    }//GEN-LAST:event_jTextFieldPrecoFocusLost

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:
        jTextFieldCodigo.setText("");
        jTextFieldNome.setText("");
        jTextFieldQuantidade.setText("");
        jTextFieldCritico.setText("");
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jLabelXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelXMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelXMouseClicked

    private void jFormattedTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldFocusGained
        double quantidade = Double.parseDouble(jTextFieldQuantidadeVendas.getText());
        double preco = Double.parseDouble(jTextFieldPreco.getText());
        double total = quantidade * preco;
        String totalF = String.format("%.02f", total);
        jFormattedTextField.setText(totalF);
    }//GEN-LAST:event_jFormattedTextFieldFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        Produtos[] prod = new Produtos[10];
        prod[0] = new Produtos("1", "Celular", 150, 15);
        prod[1] = new Produtos("2", "Sapato", 75, 7);
        prod[2] = new Produtos("3", "Geladeira", 215, 21);
        prod[3] = new Produtos("4", "Fogão", 170, 17);

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProdutosVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProdutosVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProdutosVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProdutosVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProdutosVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonLimparVenda;
    private javax.swing.JButton jButtonVenda;
    private javax.swing.JFormattedTextField jFormattedTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAvisoTexto;
    private javax.swing.JLabel jLabelX;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableProdutos;
    private javax.swing.JTable jTableVendas;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldCodigoProd;
    private javax.swing.JTextField jTextFieldCodigoVenda;
    private javax.swing.JTextField jTextFieldCritico;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPreco;
    private javax.swing.JTextField jTextFieldQuantidade;
    private javax.swing.JTextField jTextFieldQuantidadeVendas;
    // End of variables declaration//GEN-END:variables
}
